# Generated by Django 6.0.3 on 2026-03-20 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='test',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='test',
            name='code',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
