# Generated by Django 6.0.3 on 2026-03-23 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='s3_key',
            field=models.CharField(blank=True, default='', max_length=512),
        ),
    ]
