# Generated by Django 6.0.3 on 2026-03-12 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="VectorStoreConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "backend_class",
                    models.CharField(
                        default="documents.services.vector_store.ChromaVectorStore",
                        help_text="Full Python path to vector store backend class",
                        max_length=255,
                    ),
                ),
                ("is_enabled", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name_plural": "Vector Store Config",
            },
        ),
    ]
