# Generated by Django 6.0.3 on 2026-03-12 21:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0002_vectorstoreconfig"),
    ]

    operations = [
        migrations.DeleteModel(
            name="VectorStoreConfig",
        ),
    ]
