# Generated by Django 6.0.3 on 2026-03-24 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_document_s3_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('ready', 'Ready'), ('topics_extracted', 'Topics Extracted'), ('error', 'Error')], default='pending', max_length=20),
        ),
    ]
